# Generated by Django 2.0.2 on 2018-09-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('published_at', models.DateTimeField()),
                ('body', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
